; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26729.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Migs104\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
